### ISSUE TITLE
is v3 docker image working ?

### ISSUE THREAD

**Issue by devheroo** [ThisIsQasim/TastyIgniter#4]
Hi @ThisIsQasim , 
Thanks so much for your great work on these docker images.
I am trying to run docker compose on v3 branch and I am only getting this test page ( screenshot )

is this normal ? is it possible to to run the actual web app similar to what you did for v2 ? 
Thanks

![image](https://user-images.githubusercontent.com/17187711/92080933-fa7e9d80-edca-11ea-95da-9e7db08db9ab.png)

**Comment by ThisIsQasim** [comment]
Thank you for the appreciation.

The v3 branch isn't ready yet since tastyigniter v3 stable hasn't been released. Currently it fails to detect if the app is using https or http so I hardcoded it to always serve assets over https. If you run it behind an SSL proxy it'll work fine. I'll probably do a proper fix once v3 is officially released from upstream.

**Comment by devheroo** [comment]
Got it, thanks for getting back to me and I am looking forward for the next update :)
